/**
 * Writing output into a TSH install.
 *
 * The one thing this must never do is clobber someone's hand-written layout.
 * Generated files carry a marker comment; anything without it that we did not
 * write ourselves is skipped and reported back rather than overwritten.
 */

import { createHash } from 'node:crypto';
import { existsSync } from 'node:fs';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, isAbsolute, join, normalize, relative, resolve } from 'node:path';
import type { EmittedFile, WriteReport, WriteRequest } from '@shared/ipc';

/** Present in every file this app generates. */
export const GENERATED_MARKER = 'Generated by TSH Layout Creator';

/**
 * Guard against a malformed or malicious `path` escaping the layout directory.
 * Emitted paths are built from sanitised folder names, but this is the last
 * line before a write, so it checks rather than assumes.
 */
function safeJoin(base: string, candidate: string): string | undefined {
  const target = resolve(base, normalize(candidate));
  const rel = relative(resolve(base), target);
  // Empty means the candidate resolved to the base directory itself, which is
  // never a valid write target.
  if (!rel || rel.startsWith('..') || isAbsolute(rel)) return undefined;
  return target;
}

function looksGenerated(contents: string): boolean {
  // Only the first part of the file is inspected — the marker always sits in
  // the leading banner comment.
  return contents.slice(0, 2000).includes(GENERATED_MARKER);
}

/**
 * JSON has no comments, so `settings.json` can't carry the marker. Those are
 * safe to overwrite only when they parse as JSON and contain nothing we would
 * not have written.
 */
function settingsIsOverwritable(contents: string): boolean {
  try {
    const parsed: unknown = JSON.parse(contents);
    if (typeof parsed !== 'object' || parsed === null) return false;
    const keys = Object.keys(parsed as Record<string, unknown>);
    return keys.every((k) => k === 'assets' || k === 'japanese_transcription');
  } catch {
    return false;
  }
}

async function isOverwritable(path: string, file: EmittedFile): Promise<boolean> {
  let existing: string;
  try {
    existing = await readFile(path, 'utf8');
  } catch {
    return true; // Doesn't exist yet.
  }
  if (file.kind === 'json') return settingsIsOverwritable(existing);
  return looksGenerated(existing);
}

export async function writeFiles(request: WriteRequest): Promise<WriteReport> {
  const report: WriteReport = { written: [], skipped: [] };

  if (!existsSync(request.layoutDir)) {
    report.skipped.push({
      path: request.layoutDir,
      reason: 'Layout folder does not exist.',
    });
    return report;
  }

  for (const file of request.files) {
    const target = safeJoin(request.layoutDir, file.path);
    if (!target) {
      report.skipped.push({
        path: file.path,
        reason: 'Resolved outside the layout folder.',
      });
      continue;
    }

    if (!request.allowOverwriteForeign && !(await isOverwritable(target, file))) {
      report.skipped.push({
        path: file.path,
        reason: 'Existing file was not generated by this app.',
      });
      continue;
    }

    try {
      await mkdir(dirname(target), { recursive: true });
      await writeFile(target, file.contents, 'utf8');
      report.written.push(file.path);
    } catch (err) {
      report.skipped.push({
        path: file.path,
        reason: err instanceof Error ? err.message : String(err),
      });
    }
  }

  return report;
}

export async function buildZip(
  files: EmittedFile[],
): Promise<Buffer> {
  const { default: JSZip } = await import('jszip');
  const zip = new JSZip();
  for (const file of files) {
    zip.file(file.path, file.contents);
  }
  return zip.generateAsync({ type: 'nodebuffer', compression: 'DEFLATE' });
}

export function hashFiles(files: EmittedFile[]): string {
  const hash = createHash('sha256');
  for (const file of [...files].sort((a, b) => a.path.localeCompare(b.path))) {
    hash.update(file.path).update('\0').update(file.contents).update('\0');
  }
  return hash.digest('hex').slice(0, 16);
}

export async function readJsonFile<T>(path: string): Promise<T> {
  return JSON.parse(await readFile(path, 'utf8')) as T;
}

export async function writeJsonFile(path: string, value: unknown): Promise<void> {
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, `${JSON.stringify(value, null, 2)}\n`, 'utf8');
}

export { join as joinPath };
