/**
 * The IPC contract between the renderer and the main process.
 *
 * The renderer has no Node access — it holds the model, runs the editor and
 * generates file contents; the main process does every privileged thing
 * (filesystem, TSH discovery, sockets). Keeping the surface small and typed
 * here means both sides break loudly at compile time when it changes.
 */

import type { EmittedFile } from './emit';
import type { Pack } from './model/pack';

// Re-exported so the main process can import the file shape from one place
// alongside the request types that carry it.
export type { EmittedFile };

export interface TshInstall {
  /** Root of the TournamentStreamHelper install. */
  root: string;
  /** `<root>/layout`. */
  layoutDir: string;
  /** Whether `layout/include/globals.js` is present — the real marker. */
  valid: boolean;
  /** Detected TSH version, when it can be read. */
  version?: string;
}

export interface WriteRequest {
  layoutDir: string;
  files: EmittedFile[];
  /** Overwrite files not generated by this pack. Off by default. */
  allowOverwriteForeign: boolean;
}

export interface WriteReport {
  written: string[];
  skipped: { path: string; reason: string }[];
}

/** A layout folder discovered inside a TSH install, for the import flow. */
export interface DiscoveredLayout {
  folderName: string;
  path: string;
  htmlFiles: string[];
  hasCss: boolean;
  hasJs: boolean;
  previewImage?: string;
}

export interface ImportedLayoutFiles {
  folderName: string;
  css: string;
  js: string;
  html: Record<string, string>;
  settings?: string;
}

export interface LiveStatus {
  connected: boolean;
  url?: string;
  error?: string;
}

export interface CreatorApi {
  // Pack persistence -------------------------------------------------------
  openPack(): Promise<{ path: string; pack: Pack } | undefined>;
  openPackAt(path: string): Promise<Pack>;
  savePack(path: string | undefined, pack: Pack): Promise<string | undefined>;
  recentPacks(): Promise<string[]>;

  // TSH install ------------------------------------------------------------
  detectTsh(): Promise<TshInstall | undefined>;
  chooseTshFolder(): Promise<TshInstall | undefined>;
  listLayouts(layoutDir: string): Promise<DiscoveredLayout[]>;
  readLayout(layoutPath: string): Promise<ImportedLayoutFiles>;

  // Output -----------------------------------------------------------------
  writeFiles(request: WriteRequest): Promise<WriteReport>;
  exportZip(pack: Pack, files: EmittedFile[]): Promise<string | undefined>;

  // Live data --------------------------------------------------------------
  connectLive(url: string): Promise<LiveStatus>;
  disconnectLive(): Promise<void>;
  onLiveData(handler: (state: unknown) => void): () => void;
  onLiveStatus(handler: (status: LiveStatus) => void): () => void;

  // Misc -------------------------------------------------------------------
  revealInFolder(path: string): Promise<void>;
  appVersion(): Promise<string>;
}

/** Channel names, shared so main and preload can't drift apart. */
export const CHANNELS = {
  openPack: 'pack:open',
  openPackAt: 'pack:openAt',
  savePack: 'pack:save',
  recentPacks: 'pack:recent',
  detectTsh: 'tsh:detect',
  chooseTshFolder: 'tsh:choose',
  listLayouts: 'tsh:listLayouts',
  readLayout: 'tsh:readLayout',
  writeFiles: 'out:write',
  exportZip: 'out:zip',
  connectLive: 'live:connect',
  disconnectLive: 'live:disconnect',
  liveData: 'live:data',
  liveStatus: 'live:status',
  revealInFolder: 'shell:reveal',
  appVersion: 'app:version',
} as const;

declare global {
  interface Window {
    creator: CreatorApi;
  }
}
